CREATE DATABASE [CONTAS] COLLATE Latin1_General_CI_AS
GO
RAISERROR(N'Criar Tabela [dbo].[EMPRESA]', 0, 1) WITH NOWAIT;
GO
CREATE TABLE [dbo].[EMPRESA] (
    [idEMPRESA]  INT           IDENTITY (1, 1) NOT NULL,
    [idPESSOA]   INT           NOT NULL,
    [NOME]       VARCHAR (100) COLLATE Latin1_General_CI_AS NOT NULL,
    [COMENTARIO] VARCHAR (1)   COLLATE Latin1_General_CI_AS NOT NULL,
    CONSTRAINT [PK__EMPRESA__E984CA8F03317E3D] PRIMARY KEY CLUSTERED ([idEMPRESA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF),
    CONSTRAINT [FK__EMPRESA__PESSOA___0519C6AF] FOREIGN KEY ([idPESSOA]) REFERENCES [dbo].[PESSOA] ([idPESSOA]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
GO
RAISERROR(N'Criar Tabela [dbo].[PAGAMENTO]', 0, 1) WITH NOWAIT;
GO
CREATE TABLE [dbo].[PAGAMENTO] (
    [idPAGAMENTO]   VARCHAR (50) COLLATE Latin1_General_CI_AS NOT NULL,
    [idEMPRESA]     INT          NOT NULL,
    [idCONTA]       VARCHAR (1)  COLLATE Latin1_General_CI_AS NOT NULL,
    [DATAPAGAMENTO] DATETIME     NOT NULL,
    CONSTRAINT [PK__PAGAMENT__EAC5A53E0DAF0CB0] PRIMARY KEY CLUSTERED ([idPAGAMENTO]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF),
    CONSTRAINT [FK__PAGAMENTO__CONTA__0F975522] FOREIGN KEY ([idCONTA]) REFERENCES [dbo].[CONTA] ([idCONTA]) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT [FK__PAGAMENTO__EMPRE__108B795B] FOREIGN KEY ([idEMPRESA]) REFERENCES [dbo].[EMPRESA] ([idEMPRESA]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
GO
RAISERROR(N'Criar Tabela [dbo].[PESSOA]', 0, 1) WITH NOWAIT;
GO
CREATE TABLE [dbo].[PESSOA] (
    [idPESSOA]       INT           IDENTITY (1, 1) NOT NULL,
    [NOME]           VARCHAR (20)  COLLATE Latin1_General_CI_AS NOT NULL,
    [SOBRENOME]      VARCHAR (100) COLLATE Latin1_General_CI_AS NOT NULL,
    [SEXO]           CHAR (1)      COLLATE Latin1_General_CI_AS NOT NULL,
    [DATANASCIMENTO] DATE          NOT NULL,
    CONSTRAINT [PK__PESSOA__5C1FD06C7F60ED59] PRIMARY KEY CLUSTERED ([idPESSOA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF)
)
GO
RAISERROR(N'Criar Tabela [dbo].[CONTA]', 0, 1) WITH NOWAIT;
GO
CREATE TABLE [dbo].[CONTA] (
    [idCONTA]    VARCHAR (1) COLLATE Latin1_General_CI_AS NOT NULL,
    [idPESSOA]   INT         NOT NULL,
    [idEMPRESA]  INT         NOT NULL,
    [PERIODO]    DATE        NOT NULL,
    [VENCIMENTO] DATE        NOT NULL,
    [VALOR]      MONEY       NOT NULL,
    CONSTRAINT [PK__CONTA__ADC6036907F6335A] PRIMARY KEY CLUSTERED ([idCONTA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF),
    CONSTRAINT [FK__CONTA__EMPRESA_i__09DE7BCC] FOREIGN KEY ([idEMPRESA]) REFERENCES [dbo].[EMPRESA] ([idEMPRESA]) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT [FK__CONTA__PESSOA_id__0AD2A005] FOREIGN KEY ([idPESSOA]) REFERENCES [dbo].[PESSOA] ([idPESSOA]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
GO
RAISERROR(N'Criar Índice [dbo].[EMPRESA].[IFK_PERTENCE]', 0, 1) WITH NOWAIT;
GO
CREATE NONCLUSTERED INDEX [IFK_PERTENCE]
    ON [dbo].[EMPRESA]([idPESSOA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF)
GO
RAISERROR(N'Criar Índice [dbo].[PAGAMENTO].[IFK_NECESSITA]', 0, 1) WITH NOWAIT;
GO
CREATE NONCLUSTERED INDEX [IFK_NECESSITA]
    ON [dbo].[PAGAMENTO]([idCONTA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF)
GO
RAISERROR(N'Criar Índice [dbo].[PAGAMENTO].[IFK_POSSUI]', 0, 1) WITH NOWAIT;
GO
CREATE NONCLUSTERED INDEX [IFK_POSSUI]
    ON [dbo].[PAGAMENTO]([idEMPRESA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF)
GO
RAISERROR(N'Criar Índice [dbo].[CONTA].[IFK_PERTENCE]', 0, 1) WITH NOWAIT;
GO
CREATE NONCLUSTERED INDEX [IFK_PERTENCE]
    ON [dbo].[CONTA]([idEMPRESA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF)
GO
RAISERROR(N'Criar Índice [dbo].[CONTA].[IFK_POSSUI]', 0, 1) WITH NOWAIT;
GO
CREATE NONCLUSTERED INDEX [IFK_POSSUI]
    ON [dbo].[CONTA]([idPESSOA]) WITH (IGNORE_DUP_KEY = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, SORT_IN_TEMPDB = OFF)
GO
