CREATE database [BD_CONTAS]

USE [BD_CONTAS]
GO

-------------------TABELA---CONTA--------------------------------------------------------------------------------------

/****** Object:  Table [dbo].[CONTA]    Script Date: 07/12/2020 18:35:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONTA](
	[idCONTA] [varchar](100) NOT NULL,
	[idPESSOA] [int] NOT NULL,
	[idCREDOR] [int] NOT NULL,
	[PERIODO] [date] NOT NULL,
	[VENCIMENTO] [date] NOT NULL,
	[VALOR] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idCONTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CONTA]  WITH CHECK ADD  CONSTRAINT [FK_CONTA_CREDOR] FOREIGN KEY([idCREDOR])
REFERENCES [dbo].[CREDOR] ([idCREDOR])
GO

ALTER TABLE [dbo].[CONTA] CHECK CONSTRAINT [FK_CONTA_CREDOR]
GO

ALTER TABLE [dbo].[CONTA]  WITH CHECK ADD  CONSTRAINT [FK_CONTA_PESSOA] FOREIGN KEY([idPESSOA])
REFERENCES [dbo].[PESSOA] ([idPESSOA])
GO

ALTER TABLE [dbo].[CONTA] CHECK CONSTRAINT [FK_CONTA_PESSOA]
GO

-----------TABELA--CREDOR-------------------------------------------------------------------

USE [BD_CONTAS]
GO

/****** Object:  Table [dbo].[CREDOR]    Script Date: 07/12/2020 18:37:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CREDOR](
	[idCREDOR] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](100) NOT NULL,
	[COMENTARIO] [varchar](1) NOT NULL,
	[TIPOCREDOR] [char](8) NULL,
	[EMAIL] [varchar](50) NULL,
	[TELEFONE] [char](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[idCREDOR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


-------TABELA--PAGAMENTO----------------------------------------------------------------------

USE [BD_CONTAS]
GO

/****** Object:  Table [dbo].[PAGAMENTO]    Script Date: 07/12/2020 18:38:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PAGAMENTO](
	[idPAGAMENTO] [varchar](50) NOT NULL,
	[idCREDOR] [int] NOT NULL,
	[idCONTA] [varchar](100) NOT NULL,
	[DATAPAGAMENTO] [datetime] NOT NULL,
	[IDPESSOA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[idPAGAMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_PAGAMENTO_CONTA] FOREIGN KEY([idCONTA])
REFERENCES [dbo].[CONTA] ([idCONTA])
GO

ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [FK_PAGAMENTO_CONTA]
GO

ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_PAGAMENTO_CREDOR] FOREIGN KEY([idCREDOR])
REFERENCES [dbo].[CREDOR] ([idCREDOR])
GO

ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [FK_PAGAMENTO_CREDOR]
GO

ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_PAGAMENTO_PESSOA] FOREIGN KEY([IDPESSOA])
REFERENCES [dbo].[PESSOA] ([idPESSOA])
GO

ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [FK_PAGAMENTO_PESSOA]
GO


-----------TABELA--PESSOA-------------------------------------------------------------------------------


USE [BD_CONTAS]
GO

/****** Object:  Table [dbo].[PESSOA]    Script Date: 07/12/2020 18:40:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PESSOA](
	[idPESSOA] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](20) NOT NULL,
	[SOBRENOME] [varchar](100) NOT NULL,
	[SEXO] [char](1) NOT NULL,
	[DATANASCIMENTO] [date] NOT NULL,
	[DATACADASTRO] [datetime] NULL,
	[ATUALIZACAODADOS] [datetime] NULL,
	[ENDERECO] [varchar](100) NULL,
	[EMAIL] [varchar](50) NULL,
	[TELEFONE] [char](11) NULL,
 CONSTRAINT [PK_PESSOA] PRIMARY KEY CLUSTERED 
(
	[idPESSOA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



